### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by FRIMPONG00** [cita-bot/cita-bot#11]
Please, I need help to execute this, my knowledge about pyton isn’t really good, can someone help me please?

**Comment by reatlat** [comment]
@FRIMPONG00 you can find here only answers for your questions, not a personal help, and not for free,  I bealive, you probably can find some freelancer on fiverr or upwork, but in this case it will cost you the same as to buy a Cita from fuскing Вusтеrs.

**Comment by FRIMPONG00** [comment]
> @FRIMPONG00 you can find here only answers for your questions, not a personal help, and not for free, I bealive, you probably can find some freelancer on fiverr or upwork, but in this case it will cost you the same as to buy a Cita from fuскing Вusтеrs.

Yeah... that’s true but here they are selling them at 180€ and in my family we need total amount of 4 ;(

**Comment by reatlat** [comment]
> > @FRIMPONG00 you can find here only answers for your questions, not a personal help, and not for free, I bealive, you probably can find some freelancer on fiverr or upwork, but in this case it will cost you the same as to buy a Cita from fuскing Вusтеrs.
> 
> Yeah... that’s true but here they are selling them at 180€ and in my family we need total amount of 4 ;(

WOW 180E its crazy... I thought 30E (Asturias)  its a lot but 180!!!!!
good luck, just FYI, this app not making magic, its fishing(half-automatic process) to check available citas on website :/
