### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by FRIMPONG00** [cita-bot/cita-bot#12]
Please help me to solve this...

**Comment by reatlat** [comment]
@FRIMPONG00 First be careful before share personal data on screenshots!!! I can see your NIE, Name, Email and Phone number!!!!!
second one you have Python 2.9.1, in my experience citabot not run on my machine with python 3.9 
to resolve this issue I use pyenv
how to setup Pynev you can read here https://opensource.com/article/19/6/python-virtual-environments-mac
After you setup pyenv via home brew, you can setup local version python, I recommend using the 3.8.6

Also in the line #4 (anticaptcha_plugin_path) I see you forgot replace the `username` to your username... and your username which I see from your screenshot should be `frimpong`

after all you have to set local version of Python for citabot app,
Good luck :)

**Comment by FRIMPONG00** [comment]
> @FRIMPONG00 First be careful before share personal data on screenshots!!! I can see your NIE, Name, Email and Phone number!!!!!
> second one you have Python 2.9.1, in my experience citabot not run on my machine with python 3.9
> to resolve this issue I use pyenv
> how to setup Pynev you can read here https://opensource.com/article/19/6/python-virtual-environments-mac
> After you setup pyenv via home brew, you can setup local version python, I recommend using the 3.8.6
> 
> Also in the line #4 (anticaptcha_plugin_path) I see you forgot replace the `username` to your username... and your username which I see from your screenshot should be `frimpong`
> 
> after all you have to set local version of Python for citabot app,
> Good luck :)
> 
> PS: I do not speak Parseltongue(Python) but I saw how Harry Potter speacks when he sleeps ;)

Thank you very much!
