### ISSUE TITLE
Certificado de residencia - GRACIAS!!!!

### ISSUE THREAD

**Issue by Juanjuan12375** [cita-bot/cita-bot#16]
Hola!
Antes que nada...GRACIAS. Un trabajo excepcional.
Me encuentro intentando solicitar cita para POLICI-CERTIFICADOS (DE RESIDENCIA, DE NO RESIDENCIA Y DE CONCORDANCIA). Es sumamente IMPOSIBLE obtener uno.
Existe una posibilidad de que lo agregues? Es en Barcelona, y únicamente solicita NIE, luego ihay que indicarlo y finalmente el nombre y apellido.

Una cosa más...pero puedo intentar solucionarlo solo, no es tan importante como lo primero: no se por qué, pero dejo de funcionar. entonces borré todo y traté de seguir los pasos:
-Descargué Python.
-Ejecuté el requerimientos.txt en CMD.exe y se instaló todo bien.
-Chrome ya poseo.
-Descargué chrome driver y lo agregué a la carpeta donde se instaló python 
-Captcha no pide este tramite asi que indiqué en el codigo "auto_captcha=false"
-Guardo el archivo y ejecuto "python grab_me.py" en python y me da el siguiente error: 
" File "<stdin>", line 1
    python grab_me.py
           ^
SyntaxError: invalid syntax
>>>

Qué podrá ser?
Tengo windows 10, una compu basica...amd64, 8 de ram, etc.

Desde ya, muchas gracias.

**Comment by denya** [comment]
Hola

intenta ejecutar como

`python3  grab_me.py`

**Comment by Juanjuan12375** [comment]
Gracias! pero lamentablemente no anduvo...será algo de windows? tendre que intentar en una mac

**Comment by Juanjuan12375** [comment]
Muchas gracias! Que amable por la rapides en contestar. Comparto el codigo a continuación. Directamente no me lo ejecuta desde python, no lo abre. Solo tira error.
@dataclass
class CustomerProfile:
    anticaptcha_api_key: Optional[str] = None
    auto_captcha=false
    auto_office: bool = True
    chrome_driver_path: str = None
    chrome_profile_name: Optional[str] = None
    chrome_profile_path: Optional[str] = None
    save_artifacts: bool = False
    telegram_token: Optional[str] = None
    wait_exact_time: Optional[list] = None # [[minute, second]]

    province: Province = Province.BARCELONA
    operation_code: OperationType = OperationType.CERTIFICADOS_RESIDENCIA
    doc_type: DocType.NIE
    doc_value: str  # Passport? "*****"; Nie? "******"
    name: str *******
    country: str = "spain"
    year_of_birth: Optional[str] = None
    card_expire_date: Optional[str] = None  # "dd/mm/yyyy"
    phone: str ***********
    email: str *******@gmail.com
    offices: Optional[list] = field(default_factory=list)

**Comment by Juanjuan12375** [comment]
Thank you very much. I tried lots of things. I attached the code used and the error as well.
[code used.txt](https://github.com/cita-bot/cita-bot/files/6681533/code.used.txt)
[error.txt](https://github.com/cita-bot/cita-bot/files/6681534/error.txt)

**Comment by Juanjuan12375** [comment]
excelenteeee. Genio total. Gracias de nuevo. Como no quise meterle plata al anti-captcha para que me resuelva todo automaticamente, lo que hice fue abrir el archivo de CITA.PY y puse una alarma que se repita 20 veces cuando encuentra citas (cuando aparece el cartel de "tiene 5 minutos para bla bla bla"). Entonces si estoy cerca o usando la compu (que generalmente la tengo encima) me voy a alertar para aceptar la cita. Impecable, el tiempo que me ahorraste no te imaginas.

nota: no se absolutamente NADA de programacion, pero em gusta leer y aprender. Asi que imaginate lo dificil que fue para mi entender como instalar y modificar cosa, mirando y google, etc. ajajaj
