### ISSUE TITLE
some issue

### ISSUE THREAD

**Issue by Andymas82** [cita-bot/cita-bot#8]
Hi there!

Sorry to bother you again, but I face a new issue (pls see the screenshot)
Need your advise.
Thanks a lot!

Ps. I use Chromium instead of Chrome. 
All things required are installed. 

BR Andrei

![Screenshot from 2020-12-06 12-48-50](https://user-images.githubusercontent.com/75370976/101279416-686ba400-37c2-11eb-97a7-7f8112611347.png)

**Comment by reatlat** [comment]
@Andymas82 looks like you use Spanish characters `á` `í` `ñ` in cita.py:44 or maybe in some other place
My python not so good, but I know how to google 😂 

Try solutions below:
- https://es.stackoverflow.com/questions/83132/qu%C3%A9-es-el-error-syntaxerror-non-ascii-character-xc2-but-no-encoding-decla
- https://stackoverflow.com/questions/26899235/python-nltk-syntaxerror-non-ascii-character-xc3-in-file-sentiment-analysis

**Comment by reatlat** [comment]
@cita-bot perhaps you have to add utf-8 encoding to project files?

```
# coding=utf-8
```

**Comment by Andymas82** [comment]
@cita-bot @reatlat 

So, I've just deleted some parts of code that are not relevant to my operation and province and got a new error (pls see the screenshots) 
Need help=) Thanks!

![Screenshot from 2020-12-06 18-24-07](https://user-images.githubusercontent.com/75370976/101287462-ad0e3400-37f0-11eb-8120-6700da40f891.png)

![Screenshot from 2020-12-06 18-22-05](https://user-images.githubusercontent.com/75370976/101287464-b3041500-37f0-11eb-8c76-211ed940eefe.png)

**Comment by reatlat** [comment]
@Andymas82 no idea..  just small tip, if you use `nano` for editing code, use it with flag `-l` to show line numbers
BTW almos sure issue in how you set varibles and `str` is not defined ...

**Comment by FRIMPONG00** [comment]
> @Andymas82 no idea.. just small tip, if you use `nano` for editing code, use it with flag `-l` to show line numbers
> BTW almos sure issue in how you set varibles and `str` is not defined ...

Can you help me?
