### ISSUE TITLE
" No ha superado la validación de seguridad asociada al Captcha del servicio "

### ISSUE THREAD

**Issue by opiumcloud** [cita-bot/cita-bot#9]
Hi,

I'm trying to use your but. Yesterday it was working fine, but toady it stopped working. When it clicks submit, it can't access to the page where to select "Solicitar Cita" displaying the following error: " No ha superado la validación de seguridad asociada al Captcha del servicio", although AntiCaptcha solved the captcha request. I've tried changina AntiCaptcha API key, recloning the project in a Virtual Machine, etc but anything seems to solve it.

How could I solve it? Thanks in advance

**Comment by gelkin** [comment]
Yeah I have the same issue, I don't know is there anyone else with this problem? The script doesn't work unfortunately because of this. Probably it's something about the captcha v3 but it's hard to say

**Comment by MohamedElBoutahiri** [comment]
Hello guys, @cita-bot have you found something? Actually, it worked for a couple of hours. Then it's started showing that message for the rest of the day...literally blocked.

Google recaptcha V3 works with scores, what i achieved for a while again is trying to browse some websites like Google, YouTube, even if you log in, it gives you a better score then the message disappears just for a while, then it comes back again...
